language: go

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

go:
  - 1.13.x
  - master

script:
  - make all

after_success:
  - bash <(curl -s https://codecov.io/bash)
