language: go

os:
  - windows

arch:
  - amd64

go:
  - 1.13.x
  - master

script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make all ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./build.sh && ./test.sh ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
