language: go

jobs:
  include:
  - os: linux
    arch: amd64
    go: master
  - os: linux
    arch: arm64
    go: master
  - os: linux
    arch: ppc64le
    go: master
  - os: linux
    arch: s390x
    go: master
  - os: linux
    arch: amd64
    go: 1.13.x
  - os: osx
    arch: amd64
    go: master
  - os: windows
    arch: amd64
    go: master
  allow_failures:
  - os: windows
    arch: amd64
    go: master

script:
  - ./build.sh && ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
