language: go

os:
  - linux
  - osx
  allow_failures:
    - windows

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

go:
  - 1.13.x
  - master

script:
  - ./build.sh && ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
